version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update package.json with latest tag
          # Replace the moot version in package.json with the latest git tag.
          # Note that we must preserve the > or circle will fail due to the colons being parsed as yaml.
          command: >
            sed -i "s|\"version\": \"0.0.0\"|\"version\": \"$(git describe --tags | cut -c 1- | awk -F \- '{print $1};')\"|g" package.json && cat package.json

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm run test

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
